// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: src/protobuf/bootstrap/service/service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Src.Protobuf.Bootstrap.Service {
  public static partial class BootstrapService
  {
    static readonly string __ServiceName = "src.protobuf.bootstrap.service.BootstrapService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Src.Protobuf.Bootstrap.Models.Request> __Marshaller_src_protobuf_bootstrap_models_Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Src.Protobuf.Bootstrap.Models.Request.Parser));
    static readonly grpc::Marshaller<global::Src.Protobuf.Bootstrap.Models.Response> __Marshaller_src_protobuf_bootstrap_models_Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Src.Protobuf.Bootstrap.Models.Response.Parser));

    static readonly grpc::Method<global::Src.Protobuf.Bootstrap.Models.Request, global::Src.Protobuf.Bootstrap.Models.Response> __Method_Bootstrap = new grpc::Method<global::Src.Protobuf.Bootstrap.Models.Request, global::Src.Protobuf.Bootstrap.Models.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Bootstrap",
        __Marshaller_src_protobuf_bootstrap_models_Request,
        __Marshaller_src_protobuf_bootstrap_models_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Src.Protobuf.Bootstrap.Service.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BootstrapService</summary>
    [grpc::BindServiceMethod(typeof(BootstrapService), "BindService")]
    public abstract partial class BootstrapServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Src.Protobuf.Bootstrap.Models.Response> Bootstrap(global::Src.Protobuf.Bootstrap.Models.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BootstrapService</summary>
    public partial class BootstrapServiceClient : grpc::ClientBase<BootstrapServiceClient>
    {
      /// <summary>Creates a new client for BootstrapService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BootstrapServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BootstrapService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BootstrapServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BootstrapServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BootstrapServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Src.Protobuf.Bootstrap.Models.Response Bootstrap(global::Src.Protobuf.Bootstrap.Models.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Bootstrap(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Src.Protobuf.Bootstrap.Models.Response Bootstrap(global::Src.Protobuf.Bootstrap.Models.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Bootstrap, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Src.Protobuf.Bootstrap.Models.Response> BootstrapAsync(global::Src.Protobuf.Bootstrap.Models.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BootstrapAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Src.Protobuf.Bootstrap.Models.Response> BootstrapAsync(global::Src.Protobuf.Bootstrap.Models.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Bootstrap, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BootstrapServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BootstrapServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BootstrapServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Bootstrap, serviceImpl.Bootstrap).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BootstrapServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Bootstrap, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Src.Protobuf.Bootstrap.Models.Request, global::Src.Protobuf.Bootstrap.Models.Response>(serviceImpl.Bootstrap));
    }

  }
}
#endregion
