// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: src/protobuf/bootstrap/service/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Src.Protobuf.Bootstrap.Service {

  /// <summary>Holder for reflection information generated from src/protobuf/bootstrap/service/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for src/protobuf/bootstrap/service/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixzcmMvcHJvdG9idWYvYm9vdHN0cmFwL3NlcnZpY2Uvc2VydmljZS5wcm90",
            "bxIec3JjLnByb3RvYnVmLmJvb3RzdHJhcC5zZXJ2aWNlGipzcmMvcHJvdG9i",
            "dWYvYm9vdHN0cmFwL21vZGVscy9tb2RlbHMucHJvdG8ycgoQQm9vdHN0cmFw",
            "U2VydmljZRJeCglCb290c3RyYXASJi5zcmMucHJvdG9idWYuYm9vdHN0cmFw",
            "Lm1vZGVscy5SZXF1ZXN0Gicuc3JjLnByb3RvYnVmLmJvb3RzdHJhcC5tb2Rl",
            "bHMuUmVzcG9uc2UiAEIhqgIeU3JjLlByb3RvYnVmLkJvb3RzdHJhcC5TZXJ2",
            "aWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Src.Protobuf.Bootstrap.Models.ModelsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
